// tripass
//
// Copyright 2026 Simon Rowe (simon@wiremoons.com).
// https://github.com/wiremoons/tripass
//
// File: version.rs

use std::path::Path;

// NB: the output build date and time is dependant on the 'build.rs' included
// with the project.

// Example output:
//
// 'tripass' is version '0.1.3' built in 'Debug' mode.
// Built on 'Thu  1 Jun 2023 @ 21:35:22'.
// Compiled with 'rustc' version: '1.70.0'.
// MIT License. Copyright © 2026 Simon Rowe.
// Source: https://github.com/wiremoons/tripass

///////////////////////////////////////////////////////////////////////////////
//       PUBLIC FUNCTIONS
///////////////////////////////////////////////////////////////////////////////

// Build the output details into a String buffer 'info' then print it.
pub fn show() {
    let mut info: String = "".to_string();
    info.push_str(&format!(
        "\n'{}' is version '{}' ",
        app_name(),
        app_version()
    ));

    if isdebug() {
        info.push_str("built in 'Debug' mode.\n");
    } else {
        info.push_str("built in 'Release' mode.\n")
    }

    info.push_str(&format!("Built on '{}'.\n", compile_date()));

    info.push_str(&format!(
        "Compiled with 'rustc' version: '{}'.\n",
        rustc_version()
    ));
    info.push_str(&format!(
        "{} License. Copyright © 2026 {}.\n",
        app_license(),
        app_authors()
    ));
    info.push_str(&format!("Source: {}\n", app_repo()));
    println!("{}", info);
}

///////////////////////////////////////////////////////////////////////////////
//       PRIVATE FUNCTIONS
///////////////////////////////////////////////////////////////////////////////

// CONSTANT FUNCTIONS
// functions both run at compile time
// Reads the contents of the files generated by the 'build.rs' that contains a
// build date stamp as: "Fri 12 May 2023 @ 18:42:53" and the version of the
// 'rustc' compiler used for the build.
// returns a static string that is displayed in the version output.
const fn compile_date() -> &'static str {
    include!(concat!(env!("OUT_DIR"), "/builddate.txt"))
}
const fn rustc_version() -> &'static str {
    include!(concat!(env!("OUT_DIR"), "/rustcversion.txt"))
}

// arg(0) is the name of the running executable - extract and return it
fn app_name() -> String {
    let argzero = std::env::args()
        .nth(0)
        .expect("Application name not available from arg(0)");
    Path::new(&argzero)
        .file_name()
        .unwrap()
        .to_str()
        .unwrap()
        .into()
}

// confirm if current build is 'debug' or not (ie 'release')
fn isdebug() -> bool {
    if cfg!(debug_assertions) {
        return true;
    }
    return false;
}

// Obtain the license as stated in the 'Cargo.toml' file
fn app_license() -> String {
    option_env!("CARGO_PKG_LICENSE").unwrap().into()
}

// Obtain the source code repository as stated in the 'Cargo.toml' file
fn app_repo() -> String {
    option_env!("CARGO_PKG_REPOSITORY").unwrap().into()
}

// Obtain the applications version as stated in the 'Cargo.toml' file
fn app_version() -> String {
    option_env!("CARGO_PKG_VERSION").unwrap().into()
}

// Obtain the applications author(s) as stated in the 'Cargo.toml' file
fn app_authors() -> String {
    option_env!("CARGO_PKG_AUTHORS").unwrap().into()
}
